//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_image_H
#define METASPRITE_image_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define image_TILE_ORIGIN 0
#define image_TILE_W 8
#define image_TILE_H 8
#define image_WIDTH 32
#define image_HEIGHT 32
#define image_TILE_COUNT 11
#define image_PALETTE_COUNT 1
#define image_COLORS_PER_PALETTE 4
#define image_TOTAL_COLORS 4
#define image_PIVOT_X 0
#define image_PIVOT_Y 0
#define image_PIVOT_W 32
#define image_PIVOT_H 32

BANKREF_EXTERN(image)

extern const palette_color_t image_palettes[4];
extern const uint8_t image_tiles[176];

extern const metasprite_t* const image_metasprites[1];

#endif
