//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_map_H
#define METASPRITE_map_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define map_TILE_ORIGIN 0
#define map_TILE_W 8
#define map_TILE_H 8
#define map_WIDTH 160
#define map_HEIGHT 144
#define map_TILE_COUNT 122
#define map_PALETTE_COUNT 1
#define map_COLORS_PER_PALETTE 4
#define map_TOTAL_COLORS 4
#define map_MAP_ATTRIBUTES map_map_attributes
#define map_MAP_ATTRIBUTES_WIDTH 20
#define map_MAP_ATTRIBUTES_HEIGHT 18
#define map_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define map_MAP_ATTRIBUTES_PACKED_HEIGHT 18

BANKREF_EXTERN(map)

extern const palette_color_t map_palettes[4];
extern const uint8_t map_tiles[1952];

extern const unsigned char map_map[360];
extern const unsigned char map_map_attributes[360];

#endif
